-- default values
   -- g:UltiSnipsExpandTrigger               <tab>
   -- g:UltiSnipsListSnippets                <c-tab>
   -- g:UltiSnipsJumpForwardTrigger          <c-j>
   -- g:UltiSnipsJumpBackwardTrigger         <c-k>
-- vim.g.UltiSnipsSnippetDirecotries = {"./snippets"}
